### ISSUE TITLE
“列表”类型的注释无法更改文字？

### ISSUE THREAD

**Issue by huqifj** [SNFocus/simpleComment#5]
貌似“列表”无法更改文字？请看下面 gif 图片

![列表](https://user-images.githubusercontent.com/35552176/110079285-e3ddf100-7dc3-11eb-9d39-26c7bfa75627.gif)

这是个很棒的项目，感谢作者！

**Comment by SNFocus** [comment]
非常感谢关注   应该已经修复了

**Comment by huqifj** [comment]
已经可以使用，谢谢，我将关闭这个 issues
